### ISSUE TITLE
一些 bug 和改进建议

### ISSUE THREAD

**Issue by FoliageOwO** [qianmo2233/WSCraft#1]
**先支持一波，希望作者能带来更好的插件！**

一、首先就是插件使用问题：
1. 有时候加载插件时说 `WebSocket服务出错`，报 **java.net.BindException: Address already in use: bind**。但是设置端口我细看过了，根本不可能已经被使用。
2. 请求更新服务器总是出错，报 **java.net.ConnectException: Connection refused: connect**。不知道更新服务器是不是在国外，或者是服务器有问题。
3. **我第一次进入服务器输入 /wscraft token create 提示：`你已经拥有一个 Token 了，输入 /wscraft token view 来查看你的Token`。当我输入 /wscraft token view 时提示 `你还没有生成Token，输入 /wscraft token create 来生成一个Token`。不知道是什么原因。**
4. 直接输入 /wscraft 或者 /wscraft token 会触发 `An internal error occurred while attempting to perform this command`，建议改进。

二、其次是一个小细节：
我输入 /wscraft toekn 的时候发现竟然没报错，提示 `/wscraft toekn [view/create]`。应该是拼写错误，误把 `token` 拼成了 `toekn`。

三、最后是总结：
由于 token 生成不了导致一直没使用上 WSCraft（也有可能不是 token 的问题）：我用 python websockets 连接了一下 WSCraft，返回 JSON `{"result":"LoginFailed","code":"201"}`。

**Comment by qianmo2233** [comment]
首先很感谢您的反馈！
由于本人学业问题，已经有很长一段时间没有去关注并维护这个项目了
加上时间关系，插件开发完毕后并没有进行细致的测试，对导致如此多的问题感到抱歉
近期会一并修复这些问题，还希望关注后续的更新

**Comment by qianmo2233** [comment]
上文提到的所有问题都已经修复！
首先加载插件时出现 java.net.BindException: Address already in use: bind 可能是执行了roload导致的，这并不影响使用
更新服务器是宕机了，将来会修复
指令问题已经修复，可以正常获取token
现在可以下载最新的release了，最后还是感谢对本插件的支持
这个issue我就先关闭啦 ：)
